/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import bancopotencia.Conta;
import bancopotencia.ContaPoupanca;
import bancopotencia.Sessao;
import connection.Conection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Elder
 */
public class poupancaTela extends javax.swing.JFrame {
    
    Conection con1=new Conection(); 
    Connection connected;
    Statement st;
    ResultSet rs;
    ContaPoupanca c1;
    Conta conta1 = new Conta();
    /**
     * Creates new form poupancaTela
     */
    public poupancaTela() {
        initComponents();
        Conta conta = Sessao.getInstance().getUsuario();
        int id_conta = conta.getIdConta();
        jLabelValorSaldo1.setText(Double.toString(conta.getSaldo()));
        try {
            connected = con1.getConnection();
            String sqlSelect1 = "SELECT * FROM banco_potencia.contapoupanca where id_conta_corrente = " + id_conta;
            st = connected.createStatement();
            rs = st.executeQuery(sqlSelect1);
            if (rs.next()) {

                double saldo = rs.getDouble("rendimentos");
                int idContaPoupanca = rs.getInt("id_conta_Poupanca");
                c1= new ContaPoupanca(idContaPoupanca, saldo);
                jLabelValorSaldo.setText(Double.toString(c1.getRendimentos()));
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Aqui não nemnem");

            }
        } catch (HeadlessException | SQLException e) {
            System.err.println("Erro ao estabelecer a conexão com o banco de dados. Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelValorSaldo = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonAplicar = new javax.swing.JButton();
        jButtonResgatar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelValorSaldo1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jValorAplicar = new javax.swing.JTextField();
        jValorResgatar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("POUPANÇA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Saldo Poupança : ");

        jLabelValorSaldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorSaldo.setText("  ");

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonAplicar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAplicar.setText("APLICAR");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });

        jButtonResgatar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonResgatar.setText("RESGATAR");
        jButtonResgatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResgatarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Saldo Conta Corrente : ");

        jLabelValorSaldo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorSaldo1.setText("  ");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelValorSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jValorAplicar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonResgatar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jValorResgatar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValorSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelValorSaldo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelValorSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jValorAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jValorResgatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonResgatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        Conta conta = Sessao.getInstance().getUsuario();
        double aplicacao = Double.parseDouble(jValorAplicar.getText());
        if(jValorAplicar.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo de aplicação");
        } else {    
            if(aplicacao > 0 && aplicacao <= conta.getSaldo()){
                double novoSaldoP = aplicacao + c1.getRendimentos();
                double novoSaldoC = conta.getSaldo() - aplicacao;

                conta.setSaldo(novoSaldoC);
                try {
                    c1.setRendimentos(novoSaldoP);
                } catch (SQLException ex) {
                    Logger.getLogger(poupancaTela.class.getName()).log(Level.SEVERE, null, ex);
                }

                jLabelValorSaldo1.setText(Double.toString(conta.getSaldo()));
                jLabelValorSaldo.setText(Double.toString(c1.getRendimentos()));
                int id = c1.getIdContaPoupanca();
                connected = con1.getConnection();
                String sql = "UPDATE banco_potencia.contapoupanca SET rendimentos = '"+c1.getRendimentos()+"' WHERE (id_conta_poupanca = '"+c1.getIdContaPoupanca()+"')";
                try {
                    st.executeUpdate(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(poupancaTela.class.getName()).log(Level.SEVERE, null, ex);
                }
                String sql2 = "UPDATE banco_potencia.contacorrente SET saldo = "+conta.getSaldo()+" WHERE (id_conta_corrente = "+conta.getIdConta()+")";
                try {
                    st.executeUpdate(sql2);
                } catch (SQLException ex) {
                    Logger.getLogger(poupancaTela.class.getName()).log(Level.SEVERE, null, ex);
                }
                conta1.adicionarTransacoes(conta.getIdConta(),conta.getIdConta(),c1.getIdContaPoupanca(),"poupanca_aplicar","debito",aplicacao);
                JOptionPane.showMessageDialog(null, "Aplicacao realizado com sucesso. Novo saldo: " + novoSaldoC);

            }else{
                JOptionPane.showMessageDialog(null, "Sem saldo");
            }
        } 
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    private void jButtonResgatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResgatarActionPerformed
        // TODO add your handling code here:
        Conta conta = Sessao.getInstance().getUsuario();
        double resgate = Double.parseDouble(jValorResgatar.getText());

        if(jValorResgatar.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo de aplicação");
        } else {
            if(resgate > 0 && c1.getRendimentos() >= resgate){
                double novoSaldoP = c1.getRendimentos()- resgate  ;
                double novoSaldoC = resgate + conta.getSaldo() ;

                conta.setSaldo(novoSaldoC);

                try {
                    c1.setRendimentos(novoSaldoP);
                } catch (SQLException ex) {
                    Logger.getLogger(poupancaTela.class.getName()).log(Level.SEVERE, null, ex);
                }

                connected = con1.getConnection();
                String sql = "UPDATE banco_potencia.contapoupanca SET rendimentos = "+c1.getRendimentos()+" WHERE (id_conta_poupanca = "+c1.getIdContaPoupanca()+")";
                try {
                    st.executeUpdate(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(poupancaTela.class.getName()).log(Level.SEVERE, null, ex);
                }
                String sql2 = "UPDATE banco_potencia.contacorrente SET saldo = "+conta.getSaldo()+" WHERE (id_conta_corrente = "+conta.getIdConta()+")";
                try {
                    st.executeUpdate(sql2);
                } catch (SQLException ex) {
                    Logger.getLogger(poupancaTela.class.getName()).log(Level.SEVERE, null, ex);
                }
                conta1.adicionarTransacoes(conta.getIdConta(),conta.getIdConta(),c1.getIdContaPoupanca(),"poupanca_resgatar","credito",resgate);
                jLabelValorSaldo1.setText(Double.toString(conta.getSaldo()));
                jLabelValorSaldo.setText(Double.toString(c1.getRendimentos()));
                JOptionPane.showMessageDialog(null, "Resgate realizado com sucesso. Novo saldo: " + novoSaldoC);

            }else{
                JOptionPane.showMessageDialog(null, "Digite um valor válido.");
            }
        } 
    }//GEN-LAST:event_jButtonResgatarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(poupancaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(poupancaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(poupancaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(poupancaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new poupancaTela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JButton jButtonResgatar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelValorSaldo;
    private javax.swing.JLabel jLabelValorSaldo1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jValorAplicar;
    private javax.swing.JTextField jValorResgatar;
    // End of variables declaration//GEN-END:variables
}
